In [182]:
import numpy as np

In [183]:
a1 = np.array([2,4,5,67])

In [184]:
a1

array([ 2,  4,  5, 67])

In [185]:
type(a1)

numpy.ndarray

In [186]:
a2 = np.array([[2,3,4,5],[1,3,4,5]])

In [187]:
a2

array([[2, 3, 4, 5],
       [1, 3, 4, 5]])

In [188]:
a1.shape

(4,)

In [189]:
a2.shape

(2, 4)

In [190]:
a1.ndim, a2.ndim

(1, 2)

In [191]:
a1.dtype, a2.dtype

(dtype('int32'), dtype('int32'))

In [192]:
a1.size, a2.size

(4, 8)

In [193]:
import pandas as pd

In [194]:
df = pd.DataFrame(a2)
df

0  1  2  3
0  2  3  4  5
1  1  3  4  5

In [195]:
a3 = np.array([[[2.3,2.6, 8.6,0],[4.3,6.3,7,1.1]],[[5.1,7.5,2.6,9.6],[0,4.2,0,1.1]]])
a3

array([[[2.3, 2.6, 8.6, 0. ],
        [4.3, 6.3, 7. , 1.1]],

       [[5.1, 7.5, 2.6, 9.6],
        [0. , 4.2, 0. , 1.1]]])

In [196]:
#df = pd.DataFrame(a3)

In [197]:
ones = np.ones(4)
ones

array([1., 1., 1., 1.])

In [198]:
zeros = np.zeros((3,2),dtype=int)
zeros

array([[0, 0],
       [0, 0],
       [0, 0]])

In [199]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [200]:
range_array = np.arange(0.0,20.0,3.0)

In [201]:
range_array

array([ 0.,  3.,  6.,  9., 12., 15., 18.])

In [202]:
range_array.dtype

dtype('float64')

In [203]:
random_array = np.random.randint(0,10,size=(2,2))

In [204]:
random_array

array([[0, 8],
       [9, 0]])

In [205]:
random_array_2 = np.random.random((4,5))
random_array_2

array([[0.38984721, 0.09666275, 0.66006903, 0.82659868, 0.87192031],
       [0.61856416, 0.41021491, 0.7424822 , 0.42603109, 0.10391714],
       [0.22073963, 0.60863739, 0.46840187, 0.91800195, 0.50067678],
       [0.16027893, 0.83374265, 0.85562056, 0.94145032, 0.90129686]])

In [206]:
random_array_3 = np.random.rand(3,5)
random_array_3

array([[0.71993758, 0.73336068, 0.61909963, 0.6149412 , 0.80338325],
       [0.27272965, 0.61049591, 0.38634838, 0.4256253 , 0.99852278],
       [0.5363435 , 0.56650679, 0.43022677, 0.34123022, 0.80825139]])

In [207]:
np.unique(random_array)

array([0, 8, 9])

In [208]:
a1

array([ 2,  4,  5, 67])

In [209]:
a2

array([[2, 3, 4, 5],
       [1, 3, 4, 5]])

In [210]:
a3

array([[[2.3, 2.6, 8.6, 0. ],
        [4.3, 6.3, 7. , 1.1]],

       [[5.1, 7.5, 2.6, 9.6],
        [0. , 4.2, 0. , 1.1]]])

In [211]:
a3[0]

array([[2.3, 2.6, 8.6, 0. ],
       [4.3, 6.3, 7. , 1.1]])

In [212]:
a2[1]

array([1, 3, 4, 5])

In [213]:
a3[0][1]

array([4.3, 6.3, 7. , 1.1])

In [214]:
a3

array([[[2.3, 2.6, 8.6, 0. ],
        [4.3, 6.3, 7. , 1.1]],

       [[5.1, 7.5, 2.6, 9.6],
        [0. , 4.2, 0. , 1.1]]])

In [215]:
a3[:2,:2,:2]

array([[[2.3, 2.6],
        [4.3, 6.3]],

       [[5.1, 7.5],
        [0. , 4.2]]])

In [216]:
a4 = np.random.randint(10,size=(2,3,4,5))

In [217]:
a4

array([[[[7, 1, 0, 0, 6],
         [3, 1, 1, 2, 9],
         [0, 8, 5, 4, 6],
         [5, 2, 9, 5, 8]],

        [[4, 4, 5, 6, 6],
         [4, 9, 5, 4, 3],
         [4, 7, 0, 5, 0],
         [4, 2, 3, 2, 2]],

        [[5, 1, 7, 9, 5],
         [8, 6, 7, 8, 9],
         [4, 6, 4, 1, 2],
         [1, 7, 0, 8, 4]]],


       [[[1, 3, 5, 8, 4],
         [9, 1, 5, 0, 3],
         [3, 5, 0, 7, 8],
         [0, 7, 6, 7, 7]],

        [[8, 8, 0, 8, 3],
         [1, 2, 7, 7, 5],
         [0, 4, 8, 9, 5],
         [0, 6, 1, 9, 2]],

        [[0, 2, 0, 7, 3],
         [8, 8, 9, 4, 1],
         [0, 6, 9, 4, 6],
         [2, 3, 8, 8, 7]]]])

In [218]:
a4.shape

(2, 3, 4, 5)

In [219]:
a4.ndim

4

In [220]:
a4[:,:,:,2]

array([[[0, 1, 5, 9],
        [5, 5, 0, 3],
        [7, 7, 4, 0]],

       [[5, 5, 0, 6],
        [0, 7, 8, 1],
        [0, 9, 9, 8]]])

In [221]:
a1

array([ 2,  4,  5, 67])

In [222]:
a1+ones

array([ 3.,  5.,  6., 68.])

In [223]:
a1*a2

array([[  4,  12,  20, 335],
       [  2,  12,  20, 335]])

In [224]:
a3

array([[[2.3, 2.6, 8.6, 0. ],
        [4.3, 6.3, 7. , 1.1]],

       [[5.1, 7.5, 2.6, 9.6],
        [0. , 4.2, 0. , 1.1]]])

In [225]:
a2*a3

array([[[ 4.6,  7.8, 34.4,  0. ],
        [ 4.3, 18.9, 28. ,  5.5]],

       [[10.2, 22.5, 10.4, 48. ],
        [ 0. , 12.6,  0. ,  5.5]]])

In [226]:
a2

array([[2, 3, 4, 5],
       [1, 3, 4, 5]])

In [227]:
a4

array([[[[7, 1, 0, 0, 6],
         [3, 1, 1, 2, 9],
         [0, 8, 5, 4, 6],
         [5, 2, 9, 5, 8]],

        [[4, 4, 5, 6, 6],
         [4, 9, 5, 4, 3],
         [4, 7, 0, 5, 0],
         [4, 2, 3, 2, 2]],

        [[5, 1, 7, 9, 5],
         [8, 6, 7, 8, 9],
         [4, 6, 4, 1, 2],
         [1, 7, 0, 8, 4]]],


       [[[1, 3, 5, 8, 4],
         [9, 1, 5, 0, 3],
         [3, 5, 0, 7, 8],
         [0, 7, 6, 7, 7]],

        [[8, 8, 0, 8, 3],
         [1, 2, 7, 7, 5],
         [0, 4, 8, 9, 5],
         [0, 6, 1, 9, 2]],

        [[0, 2, 0, 7, 3],
         [8, 8, 9, 4, 1],
         [0, 6, 9, 4, 6],
         [2, 3, 8, 8, 7]]]])

In [228]:
#a2*a4

In [229]:
#a2.reshape(4)

In [230]:
a2 ** 2

array([[ 4,  9, 16, 25],
       [ 1,  9, 16, 25]], dtype=int32)

In [231]:
np.square(a2)

array([[ 4,  9, 16, 25],
       [ 1,  9, 16, 25]], dtype=int32)

In [232]:
np.log(2)

0.6931471805599453

In [233]:
np.log(a2)

array([[0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [0.        , 1.09861229, 1.38629436, 1.60943791]])

In [234]:
np.exp(a2)

array([[  7.3890561 ,  20.08553692,  54.59815003, 148.4131591 ],
       [  2.71828183,  20.08553692,  54.59815003, 148.4131591 ]])

In [235]:
massive_array = np.random.random(100000)

In [236]:
massive_array[:10]

array([0.44906645, 0.54805139, 0.67116543, 0.65593691, 0.66697026,
       0.44365967, 0.0431454 , 0.27893528, 0.18086912, 0.85815719])

In [237]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

8.33 ms ± 794 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
42.9 µs ± 650 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [238]:
np.max(a2)

5

In [239]:
np.min(a2)

1

In [240]:
a2

array([[2, 3, 4, 5],
       [1, 3, 4, 5]])

In [241]:
np.std(a2)

1.3169567191065923

In [242]:
np.std(a2)

1.3169567191065923

In [243]:
np.std(a2,axis=0)

array([0.5, 0. , 0. , 0. ])

In [244]:
np.std(a2,axis=1)

array([1.11803399, 1.47901995])

In [245]:
np.var(a2)

1.734375

In [246]:
a2

array([[2, 3, 4, 5],
       [1, 3, 4, 5]])

In [247]:
a4

array([[[[7, 1, 0, 0, 6],
         [3, 1, 1, 2, 9],
         [0, 8, 5, 4, 6],
         [5, 2, 9, 5, 8]],

        [[4, 4, 5, 6, 6],
         [4, 9, 5, 4, 3],
         [4, 7, 0, 5, 0],
         [4, 2, 3, 2, 2]],

        [[5, 1, 7, 9, 5],
         [8, 6, 7, 8, 9],
         [4, 6, 4, 1, 2],
         [1, 7, 0, 8, 4]]],


       [[[1, 3, 5, 8, 4],
         [9, 1, 5, 0, 3],
         [3, 5, 0, 7, 8],
         [0, 7, 6, 7, 7]],

        [[8, 8, 0, 8, 3],
         [1, 2, 7, 7, 5],
         [0, 4, 8, 9, 5],
         [0, 6, 1, 9, 2]],

        [[0, 2, 0, 7, 3],
         [8, 8, 9, 4, 1],
         [0, 6, 9, 4, 6],
         [2, 3, 8, 8, 7]]]])

In [248]:
a2.shape

(2, 4)

In [249]:
a4.shape

(2, 3, 4, 5)

In [250]:
a2_reshape = a2.reshape(2,4,1,1)

In [251]:
a2_reshape

array([[[[2]],

        [[3]],

        [[4]],

        [[5]]],


       [[[1]],

        [[3]],

        [[4]],

        [[5]]]])

In [252]:
#a2_reshape * a4

In [253]:
a2.T

array([[2, 1],
       [3, 3],
       [4, 4],
       [5, 5]])

In [254]:
a2_trnspose = a2.T

In [255]:
a3 = np.random.randint(10,size = (2,3))

In [256]:
a3

array([[8, 8, 9],
       [1, 0, 2]])

In [257]:
a3_reshape = a3.reshape(2,3,1,1)

In [258]:
a3_reshape * a4

array([[[[56,  8,  0,  0, 48],
         [24,  8,  8, 16, 72],
         [ 0, 64, 40, 32, 48],
         [40, 16, 72, 40, 64]],

        [[32, 32, 40, 48, 48],
         [32, 72, 40, 32, 24],
         [32, 56,  0, 40,  0],
         [32, 16, 24, 16, 16]],

        [[45,  9, 63, 81, 45],
         [72, 54, 63, 72, 81],
         [36, 54, 36,  9, 18],
         [ 9, 63,  0, 72, 36]]],


       [[[ 1,  3,  5,  8,  4],
         [ 9,  1,  5,  0,  3],
         [ 3,  5,  0,  7,  8],
         [ 0,  7,  6,  7,  7]],

        [[ 0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0]],

        [[ 0,  4,  0, 14,  6],
         [16, 16, 18,  8,  2],
         [ 0, 12, 18,  8, 12],
         [ 4,  6, 16, 16, 14]]]])

In [259]:
mat1 = np.random.randint(10, size=(2,3))
mat2 = np.random.randint(10, size=(2,3))

In [260]:
mat1,mat2

(array([[5, 5, 1],
        [9, 6, 0]]),
 array([[1, 9, 3],
        [0, 2, 3]]))

In [261]:
np.dot(mat1,mat2)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [262]:
mat3 = np.dot(mat1,mat2.T)

In [263]:
mat3

array([[53, 13],
       [63, 12]])

In [264]:
np.random.seed(0)

In [265]:
sales_amounts = np.random.randint(100,size=(5,3))
sales_amounts

array([[44, 47, 64],
       [67, 67,  9],
       [83, 21, 36],
       [87, 70, 88],
       [88, 12, 58]])

In [266]:
weekly_sales = pd.DataFrame(sales_amounts,index = ['Monday','Tuesday','Wednesday','Thursday','Friday'],
                            columns = ['A butter','B Butter','C Butter'])

In [267]:
weekly_sales

A butter  B Butter  C Butter
Monday           44        47        64
Tuesday          67        67         9
Wednesday        83        21        36
Thursday         87        70        88
Friday           88        12        58

In [268]:
prices = np.array([10,8,12])

In [269]:
prices

array([10,  8, 12])

In [270]:
prices.shape

(3,)

In [271]:
butter_prices = pd.DataFrame(prices.reshape(1,3),index=['Prices'],columns = ['A butter','B Butter','C Butter'])

In [272]:
butter_prices

A butter  B Butter  C Butter
Prices        10         8        12

In [273]:
total_sales = np.dot(weekly_sales,butter_prices)

ValueError: shapes (5,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

In [274]:
total_sales = np.dot(weekly_sales,butter_prices.T)

In [275]:
total_sales

array([[1584],
       [1314],
       [1430],
       [2486],
       [1672]])

In [276]:
butter_prices

A butter  B Butter  C Butter
Prices        10         8        12

In [277]:
weekly_sales

A butter  B Butter  C Butter
Monday           44        47        64
Tuesday          67        67         9
Wednesday        83        21        36
Thursday         87        70        88
Friday           88        12        58

In [278]:
daily_sales = weekly_sales.dot(butter_prices.T)

In [279]:
daily_sales

Prices
Monday       1584
Tuesday      1314
Wednesday    1430
Thursday     2486
Friday       1672

In [280]:
weekly_sales['Total ($)'] = daily_sales

In [281]:
weekly_sales

A butter  B Butter  C Butter  Total ($)
Monday           44        47        64       1584
Tuesday          67        67         9       1314
Wednesday        83        21        36       1430
Thursday         87        70        88       2486
Friday           88        12        58       1672

In [282]:
a1 > a2

array([[False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [283]:
a1>3

array([False,  True,  True,  True])

In [284]:
a1 ==3

array([False, False, False, False])

In [285]:
a1 < 20

array([ True,  True,  True, False])

In [286]:
a6 = a1 < 5

In [287]:
a6

array([ True,  True, False, False])

In [288]:
type(a6)

numpy.ndarray

In [289]:
a6.dtype

dtype('bool')

In [290]:
random_array

array([[0, 8],
       [9, 0]])

In [291]:
random_array_2.sort()

In [292]:
random_array_2

array([[0.09666275, 0.38984721, 0.66006903, 0.82659868, 0.87192031],
       [0.10391714, 0.41021491, 0.42603109, 0.61856416, 0.7424822 ],
       [0.22073963, 0.46840187, 0.50067678, 0.60863739, 0.91800195],
       [0.16027893, 0.83374265, 0.85562056, 0.90129686, 0.94145032]])

In [293]:
a1

array([ 2,  4,  5, 67])

In [294]:
a1.argsort()

array([0, 1, 2, 3], dtype=int64)

In [295]:
a1.argmin()

0

In [296]:
a1.argmax()

3

In [297]:
np.argmax(random_array,axis=0)

array([1, 0], dtype=int64)

In [298]:
np.argmax(random_array,axis=1)

array([1, 0], dtype=int64)

<img src = 'panda.png'/>

In [309]:
from matplotlib.image import imread

In [310]:
panda = imread('panda.png')

In [313]:
panda[:3]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]]], dtype=float32)

In [314]:
car = imread('car-photo.png')

In [316]:
car[0]

array([[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
       [0.3372549 , 0.34509805, 0.30588236, 1.        ],
       [0.20392157, 0.21568628, 0.14901961, 1.        ],
       ...,
       [0.64705884, 0.7058824 , 0.54901963, 1.        ],
       [0.59607846, 0.63529414, 0.45882353, 1.        ],
       [0.44705883, 0.47058824, 0.3372549 , 1.        ]], dtype=float32)

In [317]:
type(car)

numpy.ndarray

In [ ]:
dict